name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:latest
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: reddyaravind
        password: Prasad@123
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: reddyaravind/my-image-name:latest

    - name: Verify Docker Image
      run: |
        docker images
